### ISSUE TITLE
Support back-pressure

### ISSUE THREAD

**Issue by rogierschouten** [pekim/tedious#271] opened 2015-06-10 13:37 UTC
There seems to be no way to tell a Request to pause emitting 'row' events. This makes it impossible to stream query data onward without causing a large buffer somewhere.  The node-mysql adapter for instance has the capability to return a NodeJS ReadableStream which supports back-pressure.

**Comment by bretcope** [comment] 2015-06-12 17:37
The issue is that Tedious doesn't currently support real streaming. @arthurschreiber started a stream based conversion in [a pull request](https://github.com/pekim/tedious/pull/225) which would likely enable Tedious to support what you're looking for. Until that's completed, there's not really a good way to do what you're asking.

I'm going to close this, but feel free to continue discussion on the PR thread.

**Closed by bretcope** 2015-06-12 17:37 UTC
